apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflows-operator
rules:
  # we need to be able to see if the included/exclude annotation is applied to it
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  # we need to be able to see if resources have been created
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - cronworkflows
    verbs:
      - list
      - watch
  # we need to be able to install the controller
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - get
      - patch
      # we need to be able to escalate permissions
      - escalate
      - bind
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - patch
