apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: argoproj/argo-workflows-operator:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
