apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: argoproj/argo-workflows-operator:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp
              name: tmp
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: tmp
          emptyDir: { }