apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
# triggering
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - list
      - watch
# apply
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - get
      - update
      - escalate
      - bind
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - update
