apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/argoproj/argo/manifests/base/workflow-controller?ref=v2.12.2
  - https://github.com/argoproj/argo/manifests/namespace-install/workflow-controller-rbac?ref=v2.12.2

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: workflow-controller
    path: ./overlays/workflow-controller-deployment.yaml
